### ISSUE TITLE
Bug: when swap armor right clicking a piece on hotbat

### ISSUE THREAD

**Issue by FrahHS** [qShadxw/ArmorEquipEvent#2]
When i am wearing an armor, for example an helmet, and i right click another helmet (different material or meta)  from the 9 hotbar slots, the event in not called

**Comment by qShadxw** [comment]
Are you using other plugins that may interfere with these items? 
Anything that does anything similar to ArmorEquipEvent?

If you are using plugins, please list them.

**Comment by qShadxw** [comment]
I have confirmed the bug and working on a fix. Thank you for bringing this up.

**Comment by qShadxw** [comment]
Issue has been fixed in updated build. Thank you FrahHS.
